name: Build linux wheel

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules ðŸ–¥ï¸
        shell: bash
        run: |
          git submodule update --init
      - name: Build xsim ðŸŽ¡
        shell: bash
        run: bash scripts/build_wheel.sh
      - name: Install deps
        shell: bash
        run: sudo apt-get install -y libc6-dev-i386 gcc-multilib
      - name: Run tests âš™ï¸
        shell: bash
        run: |
          echo "module top; endmodule" > test.sv
          sudo pip3 install wheelhouse/*
          xsim test.sv -R
      - name: Upload artifact ðŸ›–
        uses: actions/upload-artifact@v2
        with:
          name: Python Wheels
          path: wheelhouse
      - name: Prepare wheel ðŸŽ¡
        if: startsWith(github.ref, 'refs/tags')
        shell: bash
        run: |
          rm -rf dist
          mv wheelhouse dist
      - name: Publish wheel ðŸŽ¡
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: keyi
          password: ${{ secrets.PYPI_PASSWORD }}
          skip_existing: true
