name: Build Python wheels

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules üñ•Ô∏è
        shell: bash
        run: |
          git submodule update --init
      - name: Build fsim üé°
        shell: bash
        run: bash scripts/build_wheel.sh
      - name: Run tests ‚öôÔ∏è
        shell: bash
        run: |
          echo "module top; endmodule" > test.sv
          sudo pip3 install wheelhouse/*
          fsim test.sv -R
      - name: Prepare wheel üé°
        if: startsWith(github.ref, 'refs/tags')
        shell: bash
        run: |
          sudo rm -rf dist
          cp -r wheelhouse dist
      - name: Upload artifact üõñ
        uses: actions/upload-artifact@v2
        with:
          name: LINUX_PYTHON_WHEEL
          path: dist

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules üñ•Ô∏è
        shell: bash
        run: |
          git submodule update --init
      - name: Build fsim üé°
        shell: bash
        run: bash scripts/build_wheel.sh
      - name: Prepare wheels
        shell: bash
        run: |
          pip3 install wheeltools
          curl -OL https://github.com/Kuree/hgdb/raw/master/scripts/fix_wheel.py
          mkdir -p wheelhouse && python3 fix_wheel.py dist/*.whl -w wheelhouse
          rm -rf dist
          cp -r wheelhouse dist
      - name: Run tests ‚öôÔ∏è
        shell: bash
        run: |
          echo "module top; endmodule" > test.sv
          pip3 install dist/*
          fsim test.sv -R
      - name: Upload artifact üõñ
        uses: actions/upload-artifact@v2
        with:
          name: MACOS_PYTHON_WHEEL
          path: dist


  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules üñ•Ô∏è
        shell: bash
        run: |
          git submodule update --init
      - name: Setup tmate session
        shell: bash
        run: |
          pacman -Sy --noconfirm tmate
          tmate -F
      - name: Build wheel
        shell: bash
        run: python3 setup.py bdist_wheel
      - name: Prepare wheels
        shell: bash
        run: |
          pip3 install wheeltools
          curl -OL https://github.com/Kuree/hgdb/raw/master/scripts/fix_wheel.py
          mkdir -p wheelhouse && python3 fix_wheel.py dist/*.whl -w wheelhouse
          rm -rf dist
          cp -r wheelhouse dist

  publish:
    runs-on: ubuntu-latest
    needs: [ linux, macos, windows ]
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Download Linux Wheel
        uses: actions/download-artifact@v2
        with:
          name: LINUX_PYTHON_WHEEL
      - name: Download macOS Wheel
        uses: actions/download-artifact@v2
        with:
          name: MACOS_PYTHON_WHEEL
      - name: Create dist folder
        shell: bash
        run: |
          mkdir dist
          mv *.whl dist
      - name: Publish wheel üé°
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: keyi
          password: ${{ secrets.PYPI_PASSWORD }}
          skip_existing: true
