name: Build linux wheel

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules ðŸ–¥ï¸
        shell: bash
        run: |
          git submodule update --init
      - name: Build xsim ðŸŽ¡
        shell: bash
        run: bash scripts/build_wheel.sh
      - name: Run tests âš™ï¸
        shell: bash
        run: |
          echo "module top; endmodule" > test.sv
          sudo pip3 install wheelhouse/*
          xsim test.sv -R
      - name: Prepare wheel ðŸŽ¡
        if: startsWith(github.ref, 'refs/tags')
        shell: bash
        run: |
          sudo rm -rf dist
          cp -r wheelhouse dist
      - name: Upload artifact ðŸ›–
        uses: actions/upload-artifact@v2
        with:
          name: LINUX_PYTHON_WHEEL
          path: dist

  macos:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules ðŸ–¥ï¸
        shell: bash
        run: |
          git submodule update --init
      - name: Build xsim ðŸŽ¡
        shell: bash
        run: bash scripts/build_wheel.sh
      - name: Run tests âš™ï¸
        shell: bash
        run: |
          echo "module top; endmodule" > test.sv
          pip3 install dist/*
          xsim test.sv -R
      - name: Upload artifact ðŸ›–
        uses: actions/upload-artifact@v2
        with:
          name: MACOS_PYTHON_WHEEL
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: [ linux, macos]
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Download Linux Wheel
        uses: actions/download-artifact@v2
        with:
          name: LINUX_PYTHON_WHEEL
      - name: Download macOS Wheel
        uses: actions/download-artifact@v2
        with:
          name: MACOS_PYTHON_WHEEL
      - name: Publish wheel ðŸŽ¡
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: keyi
          password: ${{ secrets.PYPI_PASSWORD }}
          skip_existing: true
